# Generated by Django 5.0.4 on 2024-04-05 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatamapLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=56)),
                ('sheet', models.CharField(max_length=56)),
                ('cellref', models.CharField(max_length=5)),
                ('de', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamap.datamap')),
            ],
        ),
    ]
