# Generated by Django 5.0.4 on 2024-04-05 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamap', '0002_datamapline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datamapline',
            old_name='de',
            new_name='dm',
        ),
    ]
