# Generated by Django 5.0.4 on 2024-06-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamap', '0003_rename_de_datamapline_dm'),
    ]

    operations = [
        migrations.AddField(
            model_name='datamapline',
            name='datatype',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
